
# Plugin config from 20:04 13/05/2023 London Time


# Messages settings.
# damage-visible: damage pop-up over entity, can be false or true (by default: true)
# damage-popup-lifetime: Value determines how long the popup will last before disappearing, 25.0 by default
# damage-projectile-chat-messages: Sends "[i] Entity took x damage" message to projectile shooter, true by default
# damage-visible-to-all: Sends pop-up over entity to everyone within render distance, false by default
# damage-show-through-walls: Allows pop-up to appear through blocks and entities, true by default
messages:
  damage-visible: true
  damage-popup-lifetime: 25.0
  damage-projectile-chat-messages: true
  damage-visible-to-all: false
  damage-show-through-walls: true


# Colors for plugin
# crit-damage: colors for crit damage gradient, crit-sign is a thing that appears before damage
# default-damage: colors for non-crit damage gradient
# All colors provided in HEX format, be careful!
# Accent - colors of projectile damage message. First - main, dark-green in original, second - text, Entity name and HP damage value, third - text color of "i" inside [i]
colors:
  crit-damage:
    first: "BE2510"
    second: "FD7348"
  crit-sign:
    sign: "X"
  default-damage:
    first: "F16666"
    second: "B79191"
  accent:
    first: "25af46"
    second: "c3c3c3"
    third: "2a4858"


