name: ShowDamage
version: '${project.version}'
main: ru.xw1w1.showdamage.Main
api-version: 1.19

commands:
  disablepopup:
    permission: showdamage.disablepopup
    aliases: [ dpu ]
  #showdamage:
    #permission: showdamage.showdamage
permissions:
  showdamage.disablepopup:
    default: true
